package com.zxl.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("blog", "id", Blog.class);
		arp.addMapping("book", "id", Book.class);
		arp.addMapping("sy_menu", "id", SyMenu.class);
		arp.addMapping("sy_portal", "id", SyPortal.class);
		arp.addMapping("sy_resource", "id", SyResource.class);
		arp.addMapping("sy_role", "id", SyRole.class);
		arp.addMapping("sy_role_menu", "id", SyRoleMenu.class);
		arp.addMapping("sy_user", "id", SyUser.class);
		arp.addMapping("sy_user_role", "id", SyUserRole.class);
	}
}

