package com.zxl.model;

import com.zxl.model.base.BaseSyResource;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SyResource extends BaseSyResource<SyResource> {
	
}
