package com.zxl.model;

import com.zxl.model.base.BaseSyRoleMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SyRoleMenu extends BaseSyRoleMenu<SyRoleMenu> {
	
}
