package com.zxl.model;

import com.zxl.model.base.BaseSyUserRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SyUserRole extends BaseSyUserRole<SyUserRole> {
	
}
