package com.zxl.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSyPortal<M extends BaseSyPortal<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.String getId() {
		return getStr("id");
	}

	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}

	public java.lang.String getTitle() {
		return getStr("title");
	}

	public M setSrc(java.lang.String src) {
		set("src", src);
		return (M)this;
	}

	public java.lang.String getSrc() {
		return getStr("src");
	}

	public M setHeight(java.math.BigDecimal height) {
		set("height", height);
		return (M)this;
	}

	public java.math.BigDecimal getHeight() {
		return get("height");
	}

	public M setClosable(java.lang.String closable) {
		set("closable", closable);
		return (M)this;
	}

	public java.lang.String getClosable() {
		return getStr("closable");
	}

	public M setCollapsible(java.lang.String collapsible) {
		set("collapsible", collapsible);
		return (M)this;
	}

	public java.lang.String getCollapsible() {
		return getStr("collapsible");
	}

	public M setSeq(java.math.BigDecimal seq) {
		set("seq", seq);
		return (M)this;
	}

	public java.math.BigDecimal getSeq() {
		return get("seq");
	}

}
