package com.zxl.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSyRole<M extends BaseSyRole<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setPid(java.lang.Integer pid) {
		set("pid", pid);
		return (M)this;
	}

	public java.lang.Integer getPid() {
		return getInt("pid");
	}

	public M setText(java.lang.String text) {
		set("text", text);
		return (M)this;
	}

	public java.lang.String getText() {
		return getStr("text");
	}

	public M setSeq(java.lang.Integer seq) {
		set("seq", seq);
		return (M)this;
	}

	public java.lang.Integer getSeq() {
		return getInt("seq");
	}

	public M setDescript(java.lang.String descript) {
		set("descript", descript);
		return (M)this;
	}

	public java.lang.String getDescript() {
		return getStr("descript");
	}

}
